"""
ChatLog model — one row per chatbot exchange.

This is an observability artifact, NOT content that gets embedded.
It does NOT use ContentMixin.

sources is stored as a plain TEXT array — each element is a
human-readable label like "IntelliTrack (project)" that the
frontend renders as a source chip.
"""
import uuid
from datetime import datetime

from sqlalchemy import Boolean, DateTime, Text, func
from sqlalchemy.dialects.postgresql import ARRAY, UUID
from sqlalchemy.orm import Mapped, mapped_column

from app.core.database import Base


class ChatLog(Base):
    """Records every question/answer exchange with the chatbot."""

    __tablename__ = "chat_logs"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid.uuid4
    )
    conversation_id: Mapped[str] = mapped_column(
        Text, nullable=False, index=True
    )  # UUID string generated by the frontend per session
    question: Mapped[str] = mapped_column(Text, nullable=False)
    answer: Mapped[str] = mapped_column(Text, nullable=False)
    sources: Mapped[list[str] | None] = mapped_column(
        ARRAY(Text), nullable=True
    )  # e.g. ["IntelliTrack (project)", "Software Engineer @ Acme (work)"]
    feedback_positive: Mapped[bool | None] = mapped_column(
        Boolean, nullable=True
    )  # None = no feedback, True = thumbs up, False = thumbs down
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now()
    )
